<?php
// $Id$

/**
 * @file
 * Web service client SOAP test module.
 */

/**
 * Implements hook_default_wsclient_service().
 */
function wsclient_soap_test_default_wsclient_service() {
  $service = new WSClientServiceDescription();
  $service->name = 'geocoder';
  $service->label = 'Geocoder.us';
  $service->url = 'http://geocoder.us/dist/eg/clients/GeoCoderPHP.wsdl';
  $service->type = 'soap';

  // Add info about the SOAP service, which the user has to provide via the UI.
  $service->settings['data types'] = array(
    'geocoder_result' => array(
      'type' => 'list<struct>',
      'label' => 'Address results',
      'property info' => array(
        'number' => array('type' => 'integer'),
        'zip' => array('type' => 'integer'),
        'suffix' => array('type' => 'text'),
        'prefix' => array('type' => 'text'),
        'type' => array('type' => 'text'),
        'street' => array('type' => 'text'),
        'state' => array('type' => 'text'),
        'city' => array('type' => 'text'),
        'lat' => array('type' => 'decimal'),
        'long' => array('type' => 'decimal'),
      ),
    ),
  );
  $operation['label'] = 'Geocode an address';
  $operation['parameter']['address'] = array('type' => 'text');
  $operation['result'] = array('type' => 'geocoder_result', 'label' => 'Geocoder result');

  $service->operations['geocode_address'] = $operation;
  $services[$service->name] = $service;
  return $services;
}
