<?php
// $Id$

/**
 * @file
 * Web service client SOAP support.
 */

/**
 * Implements hook_wsclient_endpoint_types().
 */
function wsclient_soap_wsclient_endpoint_types() {
  return array(
    'soap' => array(
      'label' => t('SOAP'),
      'class' => 'WSClientSOAPEndpoint',
    ),
  );
}

/**
 * A remote endpoint types for invoking SOAP services.
 */
class WSClientSOAPEndpoint implements WSClientEndpointInterface {

  /**
   * @var WSClientServiceDescription
   */
  protected $service;

  protected $url;

  protected  $client;

  public function __construct(WSClientServiceDescription $service) {
    $this->service = $service;
    $this->url = $service->url;
  }

  public function client() {
    if (!isset($this->client)) {
      $options['exceptions'] = TRUE;
      if (!empty($this->service->settings['options'])) {
        $options += $this->service->settings['options'];
      }
      // The url has to point to a WSDL file.
      $this->client = new SOAPClient($this->url, $options);
    }
    return $this->client;
  }

  /**
   * Calls the SOAP service.
   *
   * @param string $operation
   *   The name of the operation to execute.
   * @param array $arguments
   *   Arguments to pass to the service with this operation.
   */
  public function call($operation, $arguments) {
    $client = $this->client();
    try {
      $response = $client->__soapCall($operation, $arguments);
      return $response;
    }
    catch (SoapFault $e) {
      throw new WSClientException('Error invoking the SOAP service %name, operation %operation: %error', array('%name' => $this->service->label, '%operation' => $operation, '%error' => $e->getMessage()));
    }
  }

  // This endpoint type doesn't provide events.
  public function events() {}
  public function subscribe($event) {}
  public function unsubscribe($event) {}

  // We don't provide any entites, just register rules data types.
  public function load($type, $id) {}
  public function entities() {}

  public function dataTypes() {
    if (!empty($this->service->settings['data types'])) {
      return $this->service->settings['data types'];
    }
  }

  public function formAlter(&$form, &$form_state) { }
}
