<?php
// $Id$

/**
 * @file
 * Web service client endpoint for invoking a RESTful service.
 */

/**
 * Implements hook_wsclient_endpoint_types().
 */
function wsclient_rest_wsclient_endpoint_types() {
  return array(
    'rest' => array(
      'label' => t('REST'),
      'class' => 'WSClientRESTEndpoint',
    ),
  );
}

/**
 * A remote endpoint type for invoking REST services.
 */
class WSClientRESTEndpoint implements WSClientEndpointInterface {

  /**
   * @var WSClientServiceDescription
   */
  protected $service;

  protected $url;

  /**
   * @var RestClient
   */
  protected $client;

  public function __construct(WSClientServiceDescription $service) {
    $this->service = $service;
    $this->url = $service->url;
  }

  public function client() {
    if (!isset($this->client)) {
      if (!empty($this->service->settings['formatter'])) {
        $this->client = new RestClient(NULL, $this->service->settings['formatter']);
      }
      else {
        $this->client = new RestClient(NULL, new RestClientBaseFormatter(RestClientBaseFormatter::FORMAT_JSON));
      }
      // Pass through additional curl options.
      if (!empty($this->service->settings['curl options'])) {
        $this->client->curlOpts = $this->service->settings['curl options'];
      }
    }
    return $this->client;
  }

  /**
   * Calls the REST service.
   *
   * @param string $operation
   *   The name of the operation to execute.
   * @param array $arguments
   *   Arguments to pass to the service with this operation.
   */
  public function call($operation, $arguments) {
    $operation_url = $this->service->operations[$operation]['url'];
    $client = $this->client();
    try {
      $response = $client->get($this->service->url . $operation_url, $arguments);
      return $response;
    }
    catch (RestClientException $e) {
      throw new WSClientException('Error invoking the REST service %name, operation %operation: %error', array('%name' => $this->service->label, '%operation' => $operation, '%error' => $e->getMessage()));
    }
  }

  // This endpoint type doesn't provide events.
  public function events() {}
  public function subscribe($event) {}
  public function unsubscribe($event) {}

  // TODO: Add in order to support resources.
  public function load($type, $id) {}


  public function entities() {
    if (!empty($this->service->settings['resources'])) {
      return $this->service->settings['resources'];
    }
  }

  public function dataTypes() {
    if (!empty($this->service->datatypes)) {
      return $this->service->datatypes;
    }
  }

  public function formAlter(&$form, &$form_state) { }
}
